<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="RajasekharaReddy" failures="2" tests="2" name="Test(failed)" time="0.005" errors="0" timestamp="2020-07-30T16:53:51 IST">
  <testcase classname="RunfailedTestcases.Using_testng_failed_xml" name="runfailedtestcase2" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RunfailedTestcases.Using_testng_failed_xml.runfailedtestcase2(Using_testng_failed_xml.java:18)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- runfailedtestcase2 -->
  <testcase classname="RunfailedTestcases.Using_testng_failed_xml2" name="runfailedtestcase4" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RunfailedTestcases.Using_testng_failed_xml2.runfailedtestcase4(Using_testng_failed_xml2.java:20)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- runfailedtestcase4 -->
  <testcase classname="RunfailedTestcases.Using_testng_failed_xml" name="runfailedtestcase1" time="0.0">
    <ignored/>
  </testcase> <!-- runfailedtestcase1 -->
  <testcase classname="RunfailedTestcases.Using_testng_failed_xml2" name="runfailedtestcase3" time="0.0">
    <ignored/>
  </testcase> <!-- runfailedtestcase3 -->
</testsuite> <!-- Test(failed) -->
